/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TagsRouteImport } from './routes/tags'
import { Route as SearchRouteImport } from './routes/search'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TagsIndexRouteImport } from './routes/tags.index'
import { Route as TagsTagRouteImport } from './routes/tags.$tag'
import { Route as QuestionsQuestionSlugRouteImport } from './routes/questions.$questionSlug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiTestE2eBootstrapRouteImport } from './routes/api/test/e2e/bootstrap'

const TagsRoute = TagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsIndexRoute = TagsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TagsRoute,
} as any)
const TagsTagRoute = TagsTagRouteImport.update({
  id: '/$tag',
  path: '/$tag',
  getParentRoute: () => TagsRoute,
} as any)
const QuestionsQuestionSlugRoute = QuestionsQuestionSlugRouteImport.update({
  id: '/questions/$questionSlug',
  path: '/questions/$questionSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestE2eBootstrapRoute = ApiTestE2eBootstrapRouteImport.update({
  id: '/api/test/e2e/bootstrap',
  path: '/api/test/e2e/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/tags': typeof TagsRouteWithChildren
  '/questions/$questionSlug': typeof QuestionsQuestionSlugRoute
  '/tags/$tag': typeof TagsTagRoute
  '/tags/': typeof TagsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/test/e2e/bootstrap': typeof ApiTestE2eBootstrapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/questions/$questionSlug': typeof QuestionsQuestionSlugRoute
  '/tags/$tag': typeof TagsTagRoute
  '/tags': typeof TagsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/test/e2e/bootstrap': typeof ApiTestE2eBootstrapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/tags': typeof TagsRouteWithChildren
  '/questions/$questionSlug': typeof QuestionsQuestionSlugRoute
  '/tags/$tag': typeof TagsTagRoute
  '/tags/': typeof TagsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/test/e2e/bootstrap': typeof ApiTestE2eBootstrapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/search'
    | '/tags'
    | '/questions/$questionSlug'
    | '/tags/$tag'
    | '/tags/'
    | '/api/auth/$'
    | '/api/test/e2e/bootstrap'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/search'
    | '/questions/$questionSlug'
    | '/tags/$tag'
    | '/tags'
    | '/api/auth/$'
    | '/api/test/e2e/bootstrap'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/search'
    | '/tags'
    | '/questions/$questionSlug'
    | '/tags/$tag'
    | '/tags/'
    | '/api/auth/$'
    | '/api/test/e2e/bootstrap'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  SearchRoute: typeof SearchRoute
  TagsRoute: typeof TagsRouteWithChildren
  QuestionsQuestionSlugRoute: typeof QuestionsQuestionSlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTestE2eBootstrapRoute: typeof ApiTestE2eBootstrapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tags': {
      id: '/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof TagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/': {
      id: '/tags/'
      path: '/'
      fullPath: '/tags/'
      preLoaderRoute: typeof TagsIndexRouteImport
      parentRoute: typeof TagsRoute
    }
    '/tags/$tag': {
      id: '/tags/$tag'
      path: '/$tag'
      fullPath: '/tags/$tag'
      preLoaderRoute: typeof TagsTagRouteImport
      parentRoute: typeof TagsRoute
    }
    '/questions/$questionSlug': {
      id: '/questions/$questionSlug'
      path: '/questions/$questionSlug'
      fullPath: '/questions/$questionSlug'
      preLoaderRoute: typeof QuestionsQuestionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test/e2e/bootstrap': {
      id: '/api/test/e2e/bootstrap'
      path: '/api/test/e2e/bootstrap'
      fullPath: '/api/test/e2e/bootstrap'
      preLoaderRoute: typeof ApiTestE2eBootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TagsRouteChildren {
  TagsTagRoute: typeof TagsTagRoute
  TagsIndexRoute: typeof TagsIndexRoute
}

const TagsRouteChildren: TagsRouteChildren = {
  TagsTagRoute: TagsTagRoute,
  TagsIndexRoute: TagsIndexRoute,
}

const TagsRouteWithChildren = TagsRoute._addFileChildren(TagsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  SearchRoute: SearchRoute,
  TagsRoute: TagsRouteWithChildren,
  QuestionsQuestionSlugRoute: QuestionsQuestionSlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTestE2eBootstrapRoute: ApiTestE2eBootstrapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
